### ISSUE TITLE
Store.GetBuildJobs returns jobs which are not part of the build

### ISSUE THREAD

**Issue by mazzus** [Azure/brigade#121]
When calling Store.GetBuildJobs with a build executed by brig it will return all jobs executed by brig for the same project.

The reason for this is that Store.GetBuildJobs uses the combination of project and commit as a unique identifier, but brig sets the commit to "master" for every builds.

The code lines responsible:
https://github.com/Azure/brigade/blob/32599784d6b4c591e44225d02c1fc17d65e5f32f/pkg/storage/kube/job.go#L36

and:
https://github.com/Azure/brigade/blob/32599784d6b4c591e44225d02c1fc17d65e5f32f/brigade-client/cmd/brig/commands/run.go#L112-L133

**Comment by mazzus** [comment]
It might seem like the coupling between build and commit is a issue in general. Multiple events per commit-hash will lead to similar problems.

**Comment by technosophos** [comment]
Oooo... that should definitely not be the case. IIRC, it should use the build ULID to load the build's related jobs. ULID should be distinct per build.

**Comment by technosophos** [comment]
It looks like the build ID was not correctly set in a few places on Job objects. So commit was used instead of ULID. I'm fixing this now, adding both `worker` and `build` labels to the job pods and secrets.

**Comment by technosophos** [comment]
And for what it's worth, the commit ID that appears in names was put there not for uniqueness, but to make it easier for humans to scan through the records. The ULID is the unique ID, and the typical pattern for a name has both the ULID and the commit in it.

**Comment by mazzus** [comment]
OK :+1: I was looking into solving #7 when i noticed, so now I can continue :smile: I was getting a little tired of all the old builds accumulating.

**Comment by technosophos** [comment]
Thanks for pointing out the error. That one endpoint on the API server isn't one we use much, so this bug has gone unnoticed for too long.

A while back, we transitioned from a relatively weak identity system oriented entirely around Git toward one that was generic. It looks like somewhere along the line, we missed setting the new ID on the job pods.

Now that I know about the bug, I'm checking a few other places that could have been missed along the way. But if you're bored, you can try building from that #122 branch and see if that fixes it. (It will only work on new builds, though, since it changes a few of the pod labels.)

**Comment by mazzus** [comment]
No need to than for finding bugs, I like the project :slightly_smiling_face: I was wondering why the rest of the project used ULID while this part used commits, now I know why! I might try to build from #122 later if i have the time.
