### ISSUE TITLE
Use ConfigMap or CustomResourceDefinition instead of Secret for config

### ISSUE THREAD

**Issue by julianvmodesto** [Azure/brigade#419]
Would it be possible now to use a ConfigMap or CustomResourceDefinition instead of a Secret for Brigade proejct config? 

Quoted from [design.md](https://github.com/Azure/brigade/blob/master/docs/topics/design.md#reasoning-for-certain-design-decisions):

> At various points, we explored using TPRs and later CRDs. But the feature sets and stability of these two facilities never reached a satisfactorily stable point. So we use secrets for configuration data. Secrets have the following benefits:
>    (1) They are mountable via the volume system, a feature we use frequently
>    (2) They can be injected as environment variables
>    (3) They benefit from Kubernetes improvements to secret storage

(1) and (2) are true for ConfigMaps as well.

Could you elaborate on (3)? What improvements to secret storage?

Besides the reasons above, why would ConfigMaps and CRDs not be ideal? What would we have to do to convert?

The reason I'd like to use ConfigMaps is to be able to save my Brigade project config in source. Right now, this is possible only if I define my Brigade project [as a Helm chart](https://github.com/Azure/brigade/blob/master/charts/brigade-project/templates/secret.yaml) because the `b64enc` is used. I'm not using Helm, so storing a base64 encoded Secret in VCS is not ideal and hard to change.

I'd be happier if, as a Brigade user, I could configure most of my project in a ConfigMap and some sensitive data in a Secret.

**Comment by technosophos** [comment]
The reason we store project config in secrets is that the information in a project configuration is considered secret. It may contain, for example, tokens, pass phrases, and other such information. Supposedly at some point in the nearish future, base64 will be augmented with true encryption. So there will eventually be a real reason to use Kubernetes secrets.

There are a few tricks in the Kubernetes docs for generating Kubernetes secrets from plaintext flat files: https://kubernetes.io/docs/concepts/configuration/secret/ That might help your use case.

If someone feels up to doing the work necessary to support ConfigMaps as an alternative for storing project configuration, we'd consider the patch as long as secrets remained the default option.

**Comment by julianvmodesto** [comment]
Gotcha. Sounds like ideally we could have most config in a ConfigMap and then any secret config in a Secret. Would a patch like that be considered?

**Comment by bacongobbler** [comment]
Hey! I'm not quite sure I understand the use case for this particular feature request. Can you elaborate a bit more on what you're attempting to solve by allowing project configuration to be stored in a configmap/CRD?

With our current understanding we probably wouldn't accept a patch to split project configuration into two separate kubernetes resources so I'd hold off on a PR until we gain a better understanding of the problem first. :)

**Comment by julianvmodesto** [comment]
Sure thing!

As a Brigade user, when I create a new Brigade project config, I want to do so without Helm. To do this, my ideal workflow is I'd define my ConfigMap and commit it to source control, and `kubectl create secret generic ...` the rest of the sensitive config e.g. ssh keys. This way, it's easy for me to view and maintain my Brigade project config in source, similar to if I used a Helm chart, but now I'm not committing any sensitive Secrets to my source control in plain text or base64 encoded.

**Comment by technosophos** [comment]
So I've changed my mind since yesterday. I did some reviewing of the code base, and I'm leaning against making any changes to the project storage at this point.

What I discovered was that we'd be introducing a fairly major breaking change that would impact a variety of third-party tools. Loading and processing a project goes from a trivial exercise to a comparatively complex one -- and it's something that's done in gateways and sidecar as well as in the core. While it seems like a simple toggle switch at first, in reality it means that there are a lot of higher-level decisions that result in processing complexity for gateway implementors.

I don't think the complexity trade-off is worth it. This is one part of the system where simplicity is better.

I would suggest redirecting focus back to generating the project secret. Perhaps you will find a good non-Helm pattern that other people can use.

**Comment by julianvmodesto** [comment]
Ah yes this completely makes sense, thanks for the consideration! I'll look into what my options are.

**Comment by julianvmodesto** [comment]
For reference, I found that Secret `.stringData` works (maybe we can use `.stringData` as a hint for users in the Helm Chart instead of base64ing), but I'm not sure how I feel about commiting an ssh key as well in my Secret... I'll think about this.

One follow up question -- why must the name of my project in the Secret by sha256summed? This is slightly tricky for usability / UX if a user is not Helm.

**Comment by technosophos** [comment]
Oh, that's a good idea.

We decided to hash the project name so that external webhooks (and such) can reference the project by name without leaking information. As a secondary design goal, we wanted to allow people to use ad hoc strings for names (like `ORG/PROJECT` or `My Project`) instead of forcing people to use DNS names. (Earlier, there were some similar multi-tenant considerations to prevent in-cluster leakage, but we've since decided to simply not support multi-tenant Brigade).

To manually generate the names on Mac and Linux, we just use commands like `shasum` and `openssl`.
