### ISSUE TITLE
Add custom environment variables to worker pod

### ISSUE THREAD

**Issue by TimJones** [Azure/brigade#518]
It would be handy if the controller could have a set of configurable env vars to add to the worker spec.

In my case, we use a Brigade per team, so having a `TEAM` envvar would help in sharing common jobs in a shared library, rather than having to copy it into each pipeline.

**Comment by technosophos** [comment]
Ooo... that is a cool idea. How would we go about specifying these? In the main chart so that they'd be installed/upgrade with Helm? Another route (thinking off the top of my head) could be to allow specifying an arbitrary secret or config map that would have these, and auto-attach that to every worker.

**Comment by radu-matei** [comment]
Closing in favor of #477, which offers some more context.
Feel free to comment there, or reopen if this addresses a different use case.

Thanks!
