### ISSUE TITLE
Make it easy to remove old builds manually

### ISSUE THREAD

**Issue by emmayang** [Azure/brigade#586]
Hi, 

I have a question about if it is possible to remove old builds, since during the development phase, I created about 50+ builds, and all of them are shown in Kashti dashboard. I was thinking there might be maximum number of builds setting, and latest build will replace oldest ones if exceeds the maximum number. However I found the list keeps growing, and I cannot find a way to clean them. (I tried brig cli v0.16.0, and still 3 available commands under `brig build`)

And Due to Kashti limitation, it's not sorted correctly, and I have to scroll down a really long list to find my latest build. 

I even tried delete the project, and recreat it, but still found previous builds are attached to it again. 

Sorry if this is an obvious question and something I missed in the documentation.

**Comment by technosophos** [comment]
You can run a `brigade-vacuum` run in your cluster manually by duplicating an older run of `brigade-vacuum` and modifying the env vars. I wonder if that would be a useful feature to add to `brig` itself.

**Comment by emmayang** [comment]
@technosophos thanks, I think it would be very nice and handy to have in brig command line, or even better in Kashti UI.

**Comment by technosophos** [comment]
Re-marking this as a feature request. Changed the title accordingly

**Comment by vdice** [comment]
I could see this as a handy brig command.  Perhaps ‘brig build delete <build id> <project>’ and, perhaps more useful, ‘brig build delete-all <project>’ or some such, to delete all (probably non-running) builds for a project.  

Perhaps the third enhancement as mentioned above would be to delete all builds when a project is deleted, since, at least at the time this was written, it doesn’t appear to do so successfully.

**Comment by dgkanatsios** [comment]
So,
1. `brig build delete [buildID]` should delete corresponding Secret and Pod 
2. `brig build delete-all [project]` should delete all Secrets and Pods for [project] that are Succeeded

On (1), I wouldn't include [project] since the relevant command `brig build get [buildID]` does not include [project]. Thoughts? I'd like to give this a shot. cc @radu-matei

**Comment by radu-matei** [comment]
That would be fantastic, @dgkanatsios!

- I think `brig build delete [buildID]` is sufficient without the project ID as parameter, as it is consistent with  in `brig build get/list`
 
- `brig build delete-all [projectID]` would be fantastic.

Thanks for picking this up, let us know if we can help in any way!

**Comment by vdice** [comment]
Closing as https://github.com/Azure/brigade/pull/695 as been merged 🎉 !
