### ISSUE TITLE
brig v0.18.0 reports v0.17.0 for `version` command

### ISSUE THREAD

**Issue by blimmer** [Azure/brigade#659]
```
root@05894c8f756e:/# curl -Lo ./brig https://github.com/Azure/brigade/releases/download/v0.18.0/brig-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   607    0   607    0     0   2129      0 --:--:-- --:--:-- --:--:--  2129
100 30.8M  100 30.8M    0     0  2615k      0  0:00:12  0:00:12 --:--:-- 5532k
root@05894c8f756e:/# chmod +x brig
root@05894c8f756e:/# ./brig version
v0.17.0-46-ga87df02
```

**Comment by bacongobbler** [comment]
cc @vdice

**Comment by vdice** [comment]
@blimmer @bacongobbler Apologies, this last release needed a bit of manual intervention as this repo's `brigade.js` had a couple bugs (notably, [tag push detection](https://github.com/Azure/brigade/pull/657)).  Looks like my manual creation of the GH release tripped up the `brig` cli release logic.  I've since updated the binaries for the [v0.18.0](https://github.com/Azure/brigade/releases/tag/v0.18.0), if you have a chance to confirm (linux and darwin look good, need check out Windows.)

**Comment by bacongobbler** [comment]
thanks for the quick fix Vaughn :)

**Comment by blimmer** [comment]
yep, fixed - thanks!

```
root@fcc9c8eecacb:/# curl -Lo ./brig https://github.com/Azure/brigade/releases/download/v0.18.0/brig-linux-amd64
root@fcc9c8eecacb:/# chmod +x brig
root@fcc9c8eecacb:/# ./brig version
v0.18.0
```
