### ISSUE TITLE
brig cli build output complains about missing go package

### ISSUE THREAD

**Issue by jbayer** [Azure/brigade#66]
trying to build the brig cli on osx with the standard instructions:

```
go build -ldflags ' -X github.com/Azure/brigade/pkg/version.Version=' -o bin/brig ./brigade-client/cmd/brig
brigade-client/cmd/brig/main.go:7:2: cannot find package "github.com/Azure/brigade/brigade-client/cmd/brig/commands" in any of:
	/usr/local/go/src/github.com/Azure/brigade/brigade-client/cmd/brig/commands (from $GOROOT)
	/Users/jamesbayer/go/src/github.com/Azure/brigade/brigade-client/cmd/brig/commands (from $GOPATH)
make: *** [build-client] Error 1
```

**Comment by bacongobbler** [comment]
Hey! Can you post your current working directory? I’ve seen this happen with another user and it was because the user’s working directory was $GOPATH/src/github.com/$USERNAME/brigade instead of $GOPATH/src/github.com/Azure/brigade.

**Comment by jbayer** [comment]
pardon me because i'm not super savy with go, but here is the full gist showing my GOPATH.

https://gist.github.com/jbayer/28981df05cc0b6517d39d290dc9aa1ed

**Comment by jbayer** [comment]
thanks to @cppforlife tip i was able to get around this.

step 1) `git clone https://github.com/Azure/brigade /Users/jamesbayer/workspace/brigade-go/src/github.com/azure/brigade`
step 2) `export GOPATH=/Users/jamesbayer/workspace/brigade-go`
step 3) `cd /Users/jamesbayer/workspace/brigade-go/src/github.com/azure/brigade`
step 4) `make bootstrap build-client`
step 5) put the resulting `bin\brig` executable somewhere in your PATH

probably makes sense to update the README, which i'll try to PR if i can put some time aside.

**Comment by bacongobbler** [comment]
Yep! Totally understand. This is a standard (but I should also mention confusing) process with Go and is mentioned in their documentation: https://golang.org/doc/code.html#Organization

Your steps to get this working is correct. If you wouldn't mind adding these steps within the [development guide](https://github.com/Azure/brigade/blob/master/docs/topics/developers.md), that would be helpful. We skip over it because we're fairly used to the Go toolchain and how it expects users to work on their GOPATH, but putting a note on where to clone your fork would be useful information.
